# @format
openapi: 3.0.0
servers:
    - description: Development
      url: http://localhost:4000/api
info:
    description: This is an auth API
    version: "1.0.0"
    title: Auths API
    contact:
        email: alhabib607273@gmail.com
    license:
        name: Apache 2.0
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
    - name: Auth
      description: Auth Endpoints
paths:
    /auth/registration:
        post:
            summary: Register
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    example: John
                                email:
                                    type: string
                                    example: 4K5b6@example.com
                                password:
                                    type: string
                                    example: password
                                termsAndConditions:
                                    type: boolean
                                    example: true
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        example: 200
                                        format: int32
                                    message:
                                        type: string
                                        example: Register successfully
                                    data:
                                        type: object
                                        properties:
                                            accessToken:
                                                type: string
                                                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0Ij

    /auth/login:
        post:
            summary: Login
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: 4K5b6@example.com
                                password:
                                    type: string
                                    example: password
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: Login successfully
                                    data:
                                        type: object
                                        properties:
                                            accessToken:
                                                type: string
                                                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNT
    /auth/refresh-token/{refreshToken}:
        get:
            summary: Refresh Token
            tags: [Auth]
            parameters:
                - name: accessToken
                  in: path
                  description: accessToken
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: Refresh token generated successfully
                                    data:
                                        type: object
                                        properties:
                                            accessToken:
                                                type: string
                                                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0Ij
                                            refreshToken:
                                                type: string
                                                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0I
    /auth/logout/{refreshToken}:
        get:
            summary: Logout
            tags: [Auth]
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: Logout successfully

    /auth/otp/sent/registration:
        post:
            summary: Sent OTP
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: 4K5b6@example.com
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: OTP sent successfully

    /auth/otp/verify/registration:
        post:
            summary: Verify OTP
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: 4K5b6@example.com
                                otp:
                                    type: string
                                    example: 123456
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: OTP verified successfully

    /auth/otp/sent/forgot-password:
        post:
            summary: Sent OTP
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: 4K5b6@example.com
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: OTP sent successfully

    /auth/otp/verify/forgot-password:
        post:
            summary: Verify OTP
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: 4K5b6@example.com
                                otp:
                                    type: string
                                    example: 123456
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: OTP verified successfully
    /auth/otp/sent/reset-password:
        post:
            summary: Sent OTP
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: 4K5b6@example.com
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: OTP sent successfully
    /auth/otp/verify/reset-password:
        post:
            summary: Verify OTP
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: 4K5b6@example.com
                                otp:
                                    type: string
                                    example: 123456
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        type: integer
                                        format: int32
                                    message:
                                        type: string
                                        example: OTP verified successfully
components:
    responses:
        "500":
            description: Internal Server Error
            content:
                "application/json":
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                                format: int32
                                example: 500
                            error:
                                type: string
                                example: Internal Server Error
                            message:
                                type: string
                                example: We are sorry for the inconvenience. Please try again later
        "400":
            description: Bad Request
            content:
                "application/json":
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                                format: int32
                                example: 400
                            error:
                                type: string
                                example: Bad Request
                            message:
                                type: string
                                example: Bad Request
        "401":
            description: Unauthorized
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                                format: int32
                                example: 401
                            error:
                                type: string
                                example: Unauthorized
                            message:
                                type: string
                                example: You don't have the right permissions
        "404":
            description: Recource Not Found
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                                format: int32
                                example: 404
                            error:
                                type: string
                                example: Not Found
                            message:
                                type: string
                                example: Requested resource not found
